### ISSUE TITLE
issue for demo to anuraj

### ISSUE THREAD

**Issue by tilnow** [The-Yak-Collective/lunchtime-tickets#6]

**Comment by anuraj-rp** [comment]
test

**Comment by anuraj-rp** [comment]
how to close this issue?

**Comment by necopinus** [comment]
@anuraj-rp There should be a “Close issue” button below the comment box for you (I *think* you should have sufficient permissions to see this…).

![Screenshot 2022-06-11 at 09 22 01](https://user-images.githubusercontent.com/134362/173194135-f88162fd-3c7c-49a8-a99a-8e284c9d591f.png)

**Comment by anuraj-rp** [comment]
Nope I don't have it

![image](https://user-images.githubusercontent.com/1676128/173196412-6980080b-1d84-481e-af1b-f5e5e26720cc.png)

**Comment by necopinus** [comment]
@anuraj-rp Check now.

**Comment by anuraj-rp** [comment]
okay, works now.
